### PR TITLE
Updating versions

### PR DESCRIPTION
**Pull request by benjaminsavoy**
Compliance with latest versions of everything, as well as Leiningen 2.

### CODE REVIEW

**Comment by michaelneale** [comment]
Will this work with lein 1 as well? lein 2 is not released yet is it?

**Comment by benjaminsavoy** [comment]
Unfortunately not, however those who still use lein 1 could probably use the 1.0.2-SNAPSHOT version of the plugin. Leiningen 2 is still in preview mode, but that doesn't seem to stop them from putting that as primary download link.

**Comment by michaelneale** [comment]
OK, I think we should call his v2 of the lein-cloudbees plugin - what do you think? (also the build hive failures I can't do anything about - there is no lein plugin for jenkins, not sure how to set that up just yet - if you know, let me know !)

**Comment by benjaminsavoy** [comment]
Sounds good to me. I found this plugin: https://github.com/pyr/jenkins-leiningen I think it should be pretty straightforward.

**Pull request merged**
